/**
 * Embedded integrity hashes for binary builds
 * Auto-generated by build script - DO NOT EDIT MANUALLY
 */
export const EMBEDDED_HASHES: Record<string, string> = {
  license: '6a39b502d81745d39d967e84d3138d98e08578afcf83a81f51b4ecd6ca37c04b',
  registry: 'e88fe05d647f857ceccda2c33af0e8275ca66b49f3e9a7c20b7270d6585c4064',
};
